-- Seed comprehensive Indian cities into public.cities
insert into public.cities (name, state, country) values
  -- Telangana
  ('Hyderabad', 'Telangana', 'India'),
  ('Secunderabad', 'Telangana', 'India'),
  ('Warangal', 'Telangana', 'India'),
  ('Nizamabad', 'Telangana', 'India'),
  ('Karimnagar', 'Telangana', 'India'),
  ('Khammam', 'Telangana', 'India'),
  ('Ramagundam', 'Telangana', 'India'),
  ('Mahbubnagar', 'Telangana', 'India'),
  ('Nalgonda', 'Telangana', 'India'),
  ('Adilabad', 'Telangana', 'India'),
  ('Siddipet', 'Telangana', 'India'),
  ('Suryapet', 'Telangana', 'India'),
  ('Miryalaguda', 'Telangana', 'India'),
  ('Jagtial', 'Telangana', 'India'),
  ('Mancherial', 'Telangana', 'India'),

  -- Andhra Pradesh
  ('Visakhapatnam', 'Andhra Pradesh', 'India'),
  ('Vijayawada', 'Andhra Pradesh', 'India'),
  ('Guntur', 'Andhra Pradesh', 'India'),
  ('Nellore', 'Andhra Pradesh', 'India'),
  ('Kurnool', 'Andhra Pradesh', 'India'),
  ('Rajahmundry', 'Andhra Pradesh', 'India'),
  ('Tirupati', 'Andhra Pradesh', 'India'),
  ('Kakinada', 'Andhra Pradesh', 'India'),
  ('Kadapa', 'Andhra Pradesh', 'India'),
  ('Anantapur', 'Andhra Pradesh', 'India'),
  ('Vizianagaram', 'Andhra Pradesh', 'India'),
  ('Eluru', 'Andhra Pradesh', 'India'),
  ('Ongole', 'Andhra Pradesh', 'India'),
  ('Nandyal', 'Andhra Pradesh', 'India'),
  ('Machilipatnam', 'Andhra Pradesh', 'India'),
  ('Tenali', 'Andhra Pradesh', 'India'),
  ('Proddatur', 'Andhra Pradesh', 'India'),
  ('Chittoor', 'Andhra Pradesh', 'India'),
  ('Hindupur', 'Andhra Pradesh', 'India'),
  ('Bhimavaram', 'Andhra Pradesh', 'India'),
  ('Madanapalle', 'Andhra Pradesh', 'India'),
  ('Amaravati', 'Andhra Pradesh', 'India'),
  ('Srikakulam', 'Andhra Pradesh', 'India'),

  -- Karnataka
  ('Bengaluru', 'Karnataka', 'India'),
  ('Mysuru', 'Karnataka', 'India'),
  ('Hubballi-Dharwad', 'Karnataka', 'India'),
  ('Mangaluru', 'Karnataka', 'India'),
  ('Belagavi', 'Karnataka', 'India'),
  ('Kalaburagi', 'Karnataka', 'India'),
  ('Davanagere', 'Karnataka', 'India'),
  ('Ballari', 'Karnataka', 'India'),
  ('Vijayapura', 'Karnataka', 'India'),
  ('Shivamogga', 'Karnataka', 'India'),
  ('Tumakuru', 'Karnataka', 'India'),
  ('Raichur', 'Karnataka', 'India'),
  ('Bidar', 'Karnataka', 'India'),
  ('Hosapete', 'Karnataka', 'India'),
  ('Hassan', 'Karnataka', 'India'),
  ('Udupi', 'Karnataka', 'India'),
  ('Mandya', 'Karnataka', 'India'),
  ('Chikmagalur', 'Karnataka', 'India'),
  ('Kolar', 'Karnataka', 'India'),

  -- Maharashtra
  ('Mumbai', 'Maharashtra', 'India'),
  ('Pune', 'Maharashtra', 'India'),
  ('Nagpur', 'Maharashtra', 'India'),
  ('Thane', 'Maharashtra', 'India'),
  ('Nashik', 'Maharashtra', 'India'),
  ('Navi Mumbai', 'Maharashtra', 'India'),
  ('Chhatrapati Sambhaji Nagar', 'Maharashtra', 'India'),
  ('Solapur', 'Maharashtra', 'India'),
  ('Kalyan-Dombivli', 'Maharashtra', 'India'),
  ('Vasai-Virar', 'Maharashtra', 'India'),
  ('Mira-Bhayandar', 'Maharashtra', 'India'),
  ('Bhiwandi', 'Maharashtra', 'India'),
  ('Amravati', 'Maharashtra', 'India'),
  ('Nanded', 'Maharashtra', 'India'),
  ('Kolhapur', 'Maharashtra', 'India'),
  ('Sangli', 'Maharashtra', 'India'),
  ('Malegaon', 'Maharashtra', 'India'),
  ('Jalgaon', 'Maharashtra', 'India'),
  ('Akola', 'Maharashtra', 'India'),
  ('Latur', 'Maharashtra', 'India'),
  ('Dhule', 'Maharashtra', 'India'),
  ('Ahmednagar', 'Maharashtra', 'India'),
  ('Chandrapur', 'Maharashtra', 'India'),
  ('Panvel', 'Maharashtra', 'India'),
  ('Satara', 'Maharashtra', 'India'),
  ('Ratnagiri', 'Maharashtra', 'India'),
  ('Alibag', 'Maharashtra', 'India'),
  ('Shirdi', 'Maharashtra', 'India'),

  -- Delhi NCR / Haryana / UP
  ('Delhi', 'Delhi', 'India'),
  ('New Delhi', 'Delhi', 'India'),
  ('Gurugram', 'Haryana', 'India'),
  ('Noida', 'Uttar Pradesh', 'India'),
  ('Greater Noida', 'Uttar Pradesh', 'India'),
  ('Ghaziabad', 'Uttar Pradesh', 'India'),
  ('Faridabad', 'Haryana', 'India'),
  ('Sonipat', 'Haryana', 'India'),
  ('Panipat', 'Haryana', 'India'),
  ('Karnal', 'Haryana', 'India'),
  ('Ambala', 'Haryana', 'India'),
  ('Hisar', 'Haryana', 'India'),
  ('Panchkula', 'Haryana', 'India'),
  ('Rohtak', 'Haryana', 'India'),

  -- Tamil Nadu
  ('Chennai', 'Tamil Nadu', 'India'),
  ('Coimbatore', 'Tamil Nadu', 'India'),
  ('Madurai', 'Tamil Nadu', 'India'),
  ('Tiruchirappalli', 'Tamil Nadu', 'India'),
  ('Salem', 'Tamil Nadu', 'India'),
  ('Tiruppur', 'Tamil Nadu', 'India'),
  ('Erode', 'Tamil Nadu', 'India'),
  ('Tirunelveli', 'Tamil Nadu', 'India'),
  ('Vellore', 'Tamil Nadu', 'India'),
  ('Thoothukudi', 'Tamil Nadu', 'India'),
  ('Dindigul', 'Tamil Nadu', 'India'),
  ('Thanjavur', 'Tamil Nadu', 'India'),
  ('Hosur', 'Tamil Nadu', 'India'),
  ('Kanchipuram', 'Tamil Nadu', 'India'),
  ('Nagercoil', 'Tamil Nadu', 'India'),
  ('Ooty', 'Tamil Nadu', 'India'),

  -- Gujarat
  ('Ahmedabad', 'Gujarat', 'India'),
  ('Surat', 'Gujarat', 'India'),
  ('Vadodara', 'Gujarat', 'India'),
  ('Rajkot', 'Gujarat', 'India'),
  ('Bhavnagar', 'Gujarat', 'India'),
  ('Jamnagar', 'Gujarat', 'India'),
  ('Gandhinagar', 'Gujarat', 'India'),
  ('Junagadh', 'Gujarat', 'India'),
  ('Anand', 'Gujarat', 'India'),
  ('Navsari', 'Gujarat', 'India'),
  ('Morbi', 'Gujarat', 'India'),
  ('Vapi', 'Gujarat', 'India'),
  ('Valsad', 'Gujarat', 'India'),
  ('Bharuch', 'Gujarat', 'India'),
  ('Bhuj', 'Gujarat', 'India'),

  -- West Bengal
  ('Kolkata', 'West Bengal', 'India'),
  ('Howrah', 'West Bengal', 'India'),
  ('Durgapur', 'West Bengal', 'India'),
  ('Asansol', 'West Bengal', 'India'),
  ('Siliguri', 'West Bengal', 'India'),
  ('Kharagpur', 'West Bengal', 'India'),
  ('Haldia', 'West Bengal', 'India'),
  ('Darjeeling', 'West Bengal', 'India'),

  -- Uttar Pradesh
  ('Lucknow', 'Uttar Pradesh', 'India'),
  ('Kanpur', 'Uttar Pradesh', 'India'),
  ('Varanasi', 'Uttar Pradesh', 'India'),
  ('Agra', 'Uttar Pradesh', 'India'),
  ('Prayagraj', 'Uttar Pradesh', 'India'),
  ('Meerut', 'Uttar Pradesh', 'India'),
  ('Bareilly', 'Uttar Pradesh', 'India'),
  ('Aligarh', 'Uttar Pradesh', 'India'),
  ('Moradabad', 'Uttar Pradesh', 'India'),
  ('Saharanpur', 'Uttar Pradesh', 'India'),
  ('Gorakhpur', 'Uttar Pradesh', 'India'),
  ('Firozabad', 'Uttar Pradesh', 'India'),
  ('Jhansi', 'Uttar Pradesh', 'India'),
  ('Mathura', 'Uttar Pradesh', 'India'),
  ('Ayodhya', 'Uttar Pradesh', 'India'),

  -- Rajasthan
  ('Jaipur', 'Rajasthan', 'India'),
  ('Jodhpur', 'Rajasthan', 'India'),
  ('Kota', 'Rajasthan', 'India'),
  ('Bikaner', 'Rajasthan', 'India'),
  ('Ajmer', 'Rajasthan', 'India'),
  ('Udaipur', 'Rajasthan', 'India'),
  ('Bhilwara', 'Rajasthan', 'India'),
  ('Alwar', 'Rajasthan', 'India'),
  ('Sikar', 'Rajasthan', 'India'),
  ('Sri Ganganagar', 'Rajasthan', 'India'),

  -- Kerala
  ('Kochi', 'Kerala', 'India'),
  ('Thiruvananthapuram', 'Kerala', 'India'),
  ('Kozhikode', 'Kerala', 'India'),
  ('Thrissur', 'Kerala', 'India'),
  ('Kollam', 'Kerala', 'India'),
  ('Kannur', 'Kerala', 'India'),
  ('Alappuzha', 'Kerala', 'India'),
  ('Kottayam', 'Kerala', 'India'),
  ('Palakkad', 'Kerala', 'India'),
  ('Malappuram', 'Kerala', 'India'),

  -- Madhya Pradesh
  ('Indore', 'Madhya Pradesh', 'India'),
  ('Bhopal', 'Madhya Pradesh', 'India'),
  ('Jabalpur', 'Madhya Pradesh', 'India'),
  ('Gwalior', 'Madhya Pradesh', 'India'),
  ('Ujjain', 'Madhya Pradesh', 'India'),
  ('Sagar', 'Madhya Pradesh', 'India'),
  ('Dewas', 'Madhya Pradesh', 'India'),
  ('Satna', 'Madhya Pradesh', 'India'),
  ('Ratlam', 'Madhya Pradesh', 'India'),
  ('Rewa', 'Madhya Pradesh', 'India'),

  -- Punjab & Chandigarh
  ('Chandigarh', 'Chandigarh', 'India'),
  ('Ludhiana', 'Punjab', 'India'),
  ('Amritsar', 'Punjab', 'India'),
  ('Jalandhar', 'Punjab', 'India'),
  ('Patiala', 'Punjab', 'India'),
  ('Bathinda', 'Punjab', 'India'),
  ('Mohali', 'Punjab', 'India'),
  ('Pathankot', 'Punjab', 'India'),

  -- Odisha
  ('Bhubaneswar', 'Odisha', 'India'),
  ('Cuttack', 'Odisha', 'India'),
  ('Rourkela', 'Odisha', 'India'),
  ('Berhampur', 'Odisha', 'India'),
  ('Sambalpur', 'Odisha', 'India'),
  ('Puri', 'Odisha', 'India'),

  -- Bihar
  ('Patna', 'Bihar', 'India'),
  ('Gaya', 'Bihar', 'India'),
  ('Bhagalpur', 'Bihar', 'India'),
  ('Muzaffarpur', 'Bihar', 'India'),
  ('Purnia', 'Bihar', 'India'),
  ('Darbhanga', 'Bihar', 'India'),
  ('Bihar Sharif', 'Bihar', 'India'),

  -- Jharkhand
  ('Ranchi', 'Jharkhand', 'India'),
  ('Jamshedpur', 'Jharkhand', 'India'),
  ('Dhanbad', 'Jharkhand', 'India'),
  ('Bokaro Steel City', 'Jharkhand', 'India'),
  ('Deoghar', 'Jharkhand', 'India'),
  ('Hazaribagh', 'Jharkhand', 'India'),

  -- Assam & Northeast
  ('Guwahati', 'Assam', 'India'),
  ('Silchar', 'Assam', 'India'),
  ('Dibrugarh', 'Assam', 'India'),
  ('Jorhat', 'Assam', 'India'),
  ('Shillong', 'Meghalaya', 'India'),
  ('Imphal', 'Manipur', 'India'),
  ('Agartala', 'Tripura', 'India'),
  ('Aizawl', 'Mizoram', 'India'),
  ('Kohima', 'Nagaland', 'India'),
  ('Dimapur', 'Nagaland', 'India'),
  ('Gangtok', 'Sikkim', 'India'),
  ('Itanagar', 'Arunachal Pradesh', 'India'),

  -- Chhattisgarh
  ('Raipur', 'Chhattisgarh', 'India'),
  ('Bhilai', 'Chhattisgarh', 'India'),
  ('Bilaspur', 'Chhattisgarh', 'India'),
  ('Korba', 'Chhattisgarh', 'India'),
  ('Durg', 'Chhattisgarh', 'India'),

  -- Uttarakhand
  ('Dehradun', 'Uttarakhand', 'India'),
  ('Haridwar', 'Uttarakhand', 'India'),
  ('Roorkee', 'Uttarakhand', 'India'),
  ('Haldwani', 'Uttarakhand', 'India'),
  ('Rishikesh', 'Uttarakhand', 'India'),
  ('Nainital', 'Uttarakhand', 'India'),

  -- Himachal Pradesh
  ('Shimla', 'Himachal Pradesh', 'India'),
  ('Dharamshala', 'Himachal Pradesh', 'India'),
  ('Solan', 'Himachal Pradesh', 'India'),
  ('Mandi', 'Himachal Pradesh', 'India'),
  ('Kullu', 'Himachal Pradesh', 'India'),
  ('Manali', 'Himachal Pradesh', 'India'),

  -- Goa
  ('Goa', 'Goa', 'India'),
  ('Panaji', 'Goa', 'India'),
  ('Margao', 'Goa', 'India'),
  ('Vasco da Gama', 'Goa', 'India'),
  ('Mapusa', 'Goa', 'India'),

  -- Jammu & Kashmir / Ladakh / UTs
  ('Srinagar', 'Jammu and Kashmir', 'India'),
  ('Jammu', 'Jammu and Kashmir', 'India'),
  ('Leh', 'Ladakh', 'India'),
  ('Puducherry', 'Puducherry', 'India'),
  ('Port Blair', 'Andaman and Nicobar Islands', 'India')
on conflict (name) do update set
  state = excluded.state,
  country = excluded.country;
